from django.urls import path
from .views import *


urlpatterns = [
    path("home-view", home_view, name='home_url'),
    path('logout', logout_view, name='logout_url'),
    path('', login_view, name='login_url'),
    path('banner/', banner_view, name='banner_url'),
    path('search-view/',search_view, name='search_view'),
    path('create-banner/', create_banner, name='create_banner_url'),
    path('delete-banner/<int:pk>/', delete_banner, name='delete_banner_url'),
    path('change-banner/<int:pk>/', change_banner, name='change_banner_url'),
    path('order-view/', order_view, name='order_view_url'),
    path('create-order/', create_order, name='create_order_url'),
    path('delete-order/<int:pk>/', delete_order, name='delete_order_url'),
    path('change-order/<int:pk>/', change_order, name='change_order_url'),
    path('product-view/', product_view, name='product_url'),
    path('create-product/', create_product, name='create_product_url'),
    path('delete-product/<int:pk>/', delete_product, name='delete_product_url'),
    path('change-product/<int:pk>/', change_product, name='change_product_url'),
    path('about-product/', about_product_view, name='about_product_url'),
    path('create-about-product/', create_about_product, name='create_about_product_url'),
    path('delete-about-product/<int:pk>/', delete_about_product, name='delete_about_product_url'),
    path('change-about-product/<int:pk>/', change_about_product, name='change_about_product_url'),
    path('advice-item-view/', advice_item_view, name='advice_item_url'),
    path('create-advice/', create_advice_item, name='create_advice_item_url'),
    path('delete-advice/<int:pk>/', delete_advice_item, name='delete_advice_item_url'),
    path('change-advice/<int:pk>/', change_advice_item, name='change_advice_item_url'),
    path('advice-title-view/', advice_title_view, name='advice_title_url'),
    path('create-advice-title/', create_advice_title, name='create_advice_title_url'),
    path('delete-advice-title/<int:pk>/', delete_advice_title, name='delete_advice_title_url'),
    path('change-advice-title/<int:pk>/', change_advice_title, name='change_advice_title_url'),
    path('about-company-view/', about_company_view, name='about_company_url'),
    path('create-about-company/', create_about_company, name='create_about_company_url'),
    path('delete-about-company/<int:pk>/', delete_about_company, name='delete_about_company_url'),
    path('change-about-company/<int:pk>/', change_about_company, name='change_about_company_url'),
    path('instruction-view/', instruction_view, name='instruction_url'),
    path('create-instruction/', create_instruction, name='create_instruction_url'),
    path('delete-instruction/<int:pk>/', delete_instruction, name='delete_instruction_url'),
    path('change-instruction/<int:pk>/', change_instruction, name='change_instruction_url'),
    path("fact-title-view/", fact_view, name='fact_url'),
    path('create-fact-title/', create_fact_title, name='create_fact_title_url'),
    path('delete-fact-title/<int:pk>/', delete_fact_title, name='delete_fact_title_url'),
    path('change-fact-title/<int:pk>/', change_fact_title, name='change_fact_title_url'),
    path('create-fact-item/', create_fact_item, name='create_fact_item_url'),
    path('delete-fact-item/<int:pk>/', delete_fact_item, name='delete_fact_item_url'),
    path('change-fact-item/<int:pk>/', change_fact_item, name='change_fact_item_url'),
    path('info-view/', info_view, name='info_url'),
    path('create-info/', create_info, name='create_info_url'),
    path('delete-info/<int:pk>/', delete_info, name='delete_info_url'),
    path('change-info/<int:pk>/', change_info, name='change_info_url'),
]